name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout do código
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuração do Docker
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build da imagem Docker
    - name: Build Docker Image
      run: |
        docker build -t shipay_app:latest .

    # Rodar testes com pytest
    - name: Run Tests
      run: |
        docker run --rm shipay_app:latest pytest

    # Push da imagem Docker para o repositório
    - name: Push Docker Image
      run: |
        docker tag shipay_app:latest ${{ secrets.DOCKER_USERNAME }}/shipay_app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/shipay_app:latest

    # Deploy na AWS
    - name: Deploy to AWS
      run: |
        aws ecs update-service \
          --cluster my-cluster \
          --service my-service \
          --force-new-deployment
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
